# -*- coding: utf-8 -*-
"""Copy of Telco_Customer_Churn_Capstone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12J1LkECI5uzuvss3biUiUOHgl30sk_g1

# TS Academy Capstone Project  | Group 9
## Track: Classification  
## Dataset: Telco Customer Churn (IBM)

---

## Group Members

| Name | Email | GitHub Repository |
|------|-------|------------------|
| Jemiri Daniel Taiwo | updatedan2@gmail.com | https://github.com/jemiridaniel/TS_Academy_Capstone_Project |
| Kuram John Sokomba | Sokomba16@gmail.com |  https://github.com/SokombaGit/TS_Acedemy_Capstone_project |
| Oluba Amos Oluwasegun | amosoluba@gmail.com | https://github.com/Famous-Amos1/TS-Academy-Capstone-Project |
| Mbata Chidumaga  | mbataechidumaga@gmail.com | https://github.com/chidumaga/TS_Acedemy_Capstone_Project |
| Bethel Ya'u | sheshamkaza@gmail.com | https://github.com/She-Wins/TS_Academy_Capstone_Project |
| Nwafor Deborah | nwafordeborah41@gmail.com | https://github.com/DRDEBBIE256/TS-Academy-Capstone-Project |
| Jeremiah Yusuf | jeremiahyusuf185@gmail.com | https://github.com/Jeremy-1020/TS-Academy-Capstone-Project |
| Pyagbara Prince | princepyagbara@gmail.com | https://github.com/PrinceZorzor/TS_Academy_Capstone_Project |


---

## 📊 Project Overview

### Chosen Track
**Classification Track**

### Problem Statement
Predict whether a telecom customer will churn (Yes/No) using supervised learning techniques.

### Dataset
**Telco Customer Churn Dataset (IBM)**  
Contains 7,043 customers with demographic, service, billing, and contract features.

Target variable: **Churn (Yes/No)**

---

## 🔗 GitHub Repositories

Each group member has created a repository named:

**TS_Academy_Capstone_Project**

Repository links:

- Member 1: https://github.com/jemiridaniel/TS_Academy_Capstone_Project
- Member 2: https://github.com/SokombaGit/TS_Acedemy_Capstone_project
- Member 3: https://github.com/Famous-Amos1/TS-Academy-Capstone-Project
- Member 4: https://github.com/chidumaga/TS_Acedemy_Capstone_Project
- Member 5: https://github.com/She-Wins/TS_Academy_Capstone_Project
- Member 6: https://github.com/DRDEBBIE256/TS-Academy-Capstone-Project
- Member 7: https://github.com/Jeremy-1020/TS-Academy-Capstone-Project
- Member 8: https://github.com/PrinceZorzor/TS_Academy_Capstone_Project

---

This notebook covers **all mandatory preprocessing + EDA** items and the **classification track** modeling requirements:

- Data preprocessing (cleaning, type fixes, missing values handling)
- **Full EDA**: dataset overview, missingness visuals, numeric & categorical profiling, univariate + bivariate/multivariate analysis
- Baseline model: **Logistic Regression**
- Advanced model: **Random Forest**
- Metrics: Accuracy, Precision, Recall, F1, Confusion Matrix
- **Class imbalance strategies** and comparison
- Feature interpretation (coefficients + feature importance)
- Error analysis: false positives vs false negatives + confusion matrix interpretation
"""

# Imports
import os
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
from google.colab import drive
import seaborn as sns

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_validate
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, ConfusionMatrixDisplay, classification_report
)

from google.colab import drive
drive.mount('/content/drive')

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

# 1) Load data
DATA_PATH = '/content/drive/MyDrive/TS Academy/WA_Fn-UseC_-Telco-Customer-Churn.csv'

if not os.path.exists(DATA_PATH):
    raise FileNotFoundError(
        f'Could not find file at: {DATA_PATH}\n'
        'Please confirm the path or update DATA_PATH.'
    )

df_raw = pd.read_csv(DATA_PATH)
print('Raw shape:', df_raw.shape)
display(df_raw.head())

"""## 2) Dataset Overview
Rows, columns, dtypes, memory usage, and basic descriptive statistics.
"""

# Dataset overview
df_raw.info(memory_usage='deep')

print('\nRows:', df_raw.shape[0])
print('Columns:', df_raw.shape[1])

# Basic stats (numeric)
display(df_raw.describe(include=[np.number]).T)

# Basic stats (categorical)
display(df_raw.describe(include=['object']).T)

"""**Key Numeric Statistics:**
- Tenure: Mean ≈ 32.4 months, ranges from 0 to 72 months. The wide standard deviation (~24.6) indicates a spread-out distribution — both very new and very long-term customers exist.
- MonthlyCharges: Mean ≈ \$64.76, std ≈ \$30.09. Values range from \$18.25 to \$118.75. The distribution is approximately uniform/bimodal (low-cost basic plans vs. high-cost premium plans).
- SeniorCitizen: Mean ≈ 0.16, confirming only ~16% of the customer base are senior citizens — a **heavily skewed binary variable**.

**Key Categorical Insights (from `.describe()`):**
- PhoneService: `Yes` dominates (6,361 / 7,043 ≈ 90%) — most customers subscribe to phone service.
- Contract: `Month-to-month` is the most common contract type (3,875 customers) — this group is typically at highest churn risk.
- PaymentMethod: `Electronic check` is the most used (2,365 customers).
- InternetService: `Fiber optic` leads (3,096 customers), suggesting a strong premium internet subscriber base.
- TotalCharges: Has 11 blank/space entries — these are the hidden missing values introduced by the object dtype.

## 3) Data Preprocessing
Cleaning + validation:
- Standardize column names
- Strip whitespace in string fields
- Fix `TotalCharges` numeric parsing (blanks → NaN)
- Ensure numeric fields are numeric
- Validate target `Churn` and build binary label
- Remove duplicate `customerID`
"""

# Work on a copy
df = df_raw.copy()

# Standardize column names
df.columns = [c.strip() for c in df.columns]

# Strip whitespace for object columns
for c in df.select_dtypes(include=['object']).columns:
    df[c] = df[c].astype(str).str.strip()

# customerID uniqueness
if 'customerID' in df.columns:
    before = df.shape[0]
    df = df.drop_duplicates(subset=['customerID'])
    after = df.shape[0]
    if after != before:
        print(f'Dropped {before-after} duplicate customerID rows')

# Convert TotalCharges to numeric (often stored as text)
if 'TotalCharges' in df.columns:
    df['TotalCharges'] = df['TotalCharges'].replace({'': np.nan, ' ': np.nan})
    df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

# Ensure numeric types
for col in ['tenure', 'MonthlyCharges']:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')

# SeniorCitizen should be 0/1
if 'SeniorCitizen' in df.columns:
    df['SeniorCitizen'] = pd.to_numeric(df['SeniorCitizen'], errors='coerce').fillna(0).astype(int)
    bad_sc = set(df['SeniorCitizen'].unique()) - {0, 1}
    if bad_sc:
        print('Warning: unexpected SeniorCitizen values:', bad_sc)

# Validate target
if 'Churn' not in df.columns:
    raise ValueError("Target column 'Churn' not found. Confirm this is the Telco churn dataset.")
bad_churn = set(df['Churn'].unique()) - {'Yes', 'No'}
if bad_churn:
    print('Warning: unexpected Churn values:', bad_churn)

print('Cleaned shape:', df.shape)
display(df.head())

"""## 4) Missing Values Analysis
We visualize missingness with:
- Bar chart (% missing per column)
- Heatmap-style matrix (rows x columns) showing missing patterns

"""

missing_rate = df.isna().mean().sort_values(ascending=False)
display(missing_rate[missing_rate > 0].to_frame('missing_rate'))

# Bar chart of missingness
plt.figure()
plt.bar(missing_rate.index.astype(str), (missing_rate.values * 100))
plt.title('Missing values per column (%)')
plt.xlabel('Column')
plt.ylabel('% Missing')
plt.xticks(rotation=80, ha='right')
plt.tight_layout()
plt.show()

# Missingness heatmap (boolean matrix)
# NOTE: For large datasets, we sample rows to keep it readable
sample_df = df.sample(n=min(400, len(df)), random_state=RANDOM_STATE)
miss_matrix = sample_df.isna().astype(int).values  # 1 = missing

plt.figure()
plt.imshow(miss_matrix, aspect='auto')
plt.title('Missingness pattern heatmap (sampled rows)')
plt.xlabel('Columns')
plt.ylabel('Rows (sample)')
plt.xticks(ticks=np.arange(len(sample_df.columns)), labels=sample_df.columns, rotation=90)
plt.tight_layout()
plt.show()

"""**Bar Chart (% Missing per Column):**
- Only **one column** — `TotalCharges` — has missing values, at approximately **0.16%** (11 records out of 7,043).
- All other 19 columns have **zero missing values**, confirming the dataset is largely complete and clean.
- The bar chart is **heavily right-skewed in terms of missingness** — nearly all bars are at zero with one tiny spike on `TotalCharges`.

**Missingness Heatmap (sampled rows):**
- The heatmap is almost entirely uniform (dark), confirming near-complete data across the sampled rows.

## 5) Target Variable Analysis (For Supervised Classification)
We check class distribution and imbalance.
"""

target_counts = df['Churn'].value_counts()
target_pct = df['Churn'].value_counts(normalize=True) * 100
display(pd.DataFrame({'count': target_counts, 'percent': target_pct.round(2)}))

plt.figure()
plt.bar(target_counts.index.astype(str), target_counts.values)
plt.title('Target (Churn) class distribution')
plt.xlabel('Churn')
plt.ylabel('Count')
plt.tight_layout()
plt.show()

"""**NB:** In the Telco dataset, churn rate is typically ~26%, giving a ratio of ~0.36. Thus, indicating **a moderate class imbalance** that warrants `class_weight='balanced'.

## 6) Numeric Feature Profiling
For **each numeric feature** we generate:
- Histogram
- Skewness & kurtosis
- Box plot (outliers)
- Descriptive stats (mean/median/std/min/max)
"""

# Identify numeric columns
numeric_cols = [c for c in df.columns if pd.api.types.is_numeric_dtype(df[c]) and c != 'SeniorCitizen']
# Keep SeniorCitizen as numeric but treat it like categorical (0/1) for EDA below

print('Numeric columns for profiling:', numeric_cols)

for col in numeric_cols:
    s = df[col].dropna()
    if s.empty:
        continue
    stats = {
        'count': int(s.shape[0]),
        'mean': float(s.mean()),
        'median': float(s.median()),
        'std': float(s.std()),
        'min': float(s.min()),
        'max': float(s.max()),
        'skewness': float(s.skew()),
        'kurtosis': float(s.kurtosis()),
    }
    print(f"\n--- {col} stats ---")
    for k, v in stats.items():
        print(f"{k}: {v}")

    # Histogram
    plt.figure()
    plt.hist(s, bins=30)
    plt.title(f'{col} — histogram')
    plt.xlabel(col)
    plt.ylabel('Frequency')
    plt.tight_layout()
    plt.show()

    # Box plot
    plt.figure()
    plt.boxplot(s, labels=[col])
    plt.title(f'{col} — box plot (outliers)')
    plt.tight_layout()
    plt.show()

"""### Plot Interpretation — Numerical Feature Profiles

**1. `Tenure` (Months as a Customer):**
- Distribution shape: **Bimodal** — there is a large spike at very low tenure (0–5 months) and another peak at the high end (65–72 months).
- This is **right-skewed at the low end**, meaning many customers are very new, but a significant loyal cohort has been with the company for 5–6 years.
- Box plot shows the median at ~29 months, with no extreme outliers — values are bounded by the natural contract limit of 72 months.
- **Churn implication:** New customers (low tenure) churn far more often — this is typically the highest-risk cohort.

**2. `MonthlyCharges` (\$ per Month):**
- Distribution shape: **Approximately uniform with a left spike** — there is a sharp peak of customers paying around \$18–25/month (basic plans) and then a fairly spread distribution up to \$120.
- The distribution is **slightly right-skewed** overall, with mean ≈ \$64.76 and median ≈ \$70.35.
- Box plot shows no extreme outliers — the IQR spans roughly \$35–\$90.
- **Churn implication:** Higher monthly charges correlate with higher churn rates — premium subscribers who feel overcharged are more likely to leave.

**3. `TotalCharges` (Cumulative Billing):**
- Distribution shape: **Strongly right-skewed** — the majority of customers have low total charges (new/short-tenure customers), while a long tail represents long-term customers with large cumulative bills.
- Box plot shows a median well below the mean, with a significant right tail of outliers — expected given the positive relationship with tenure.
- `TotalCharges` is largely a **function of `tenure × MonthlyCharges`**, so multicollinearity with these variables will be considered in modelling.

## 7) Categorical Feature Profiling
For **each categorical feature** we show:
- value counts
- percentage breakdown
- bar chart
"""

# Identify categorical columns
categorical_cols = [c for c in df.columns if df[c].dtype == 'object' and c != 'customerID']
# Treat SeniorCitizen as categorical for this section
if 'SeniorCitizen' in df.columns:
    categorical_cols = categorical_cols + ['SeniorCitizen']

print('Categorical columns for profiling:', categorical_cols)

for col in categorical_cols:
    vc = df[col].value_counts(dropna=False)
    pct = df[col].value_counts(normalize=True, dropna=False) * 100
    summary = pd.DataFrame({'count': vc, 'percent': pct.round(2)})
    print(f"\n--- {col} ---")
    display(summary)

    # Bar chart
    plt.figure()
    plt.bar(summary.index.astype(str), summary['count'].values)
    plt.title(f'{col} — distribution')
    plt.xlabel(col)
    plt.ylabel('Count')
    plt.xticks(rotation=60, ha='right')
    plt.tight_layout()
    plt.show()

"""### Plot Interpretation — Categorical Feature Bar Charts

**`gender`:** Nearly perfectly balanced — Male (50.5%) vs. Female (49.5%). **No skew.** Gender is unlikely to be a strong churn predictor on its own.

**`SeniorCitizen`:** Highly **left-skewed** — Non-seniors dominate (83.8%). Only ~16% are senior citizens. This is a **rare-group variable** that may still carry predictive power (seniors tend to churn at different rates).

**`Partner`:** Slight lean toward `No` (51.7% have no partner). **Near-balanced** distribution.

**`Dependents`:** Strongly **left-skewed** — 70% of customers have no dependents. Customers with dependents may be more stable (family accounts).

**`PhoneService`:** Heavily **left-skewed** — 90.3% subscribe to phone service. Very low variance; not a strong discriminating feature.

**`MultipleLines`:** Three categories — `No` (48.1%), `Yes` (42.2%), `No phone service` (9.7%). **Slightly left-skewed toward No.** Customers without multiple lines are more common.

**`InternetService`:** `Fiber optic` (44%), `DSL` (34.4%), `No` (21.7%). **Right-skewed toward high-cost Fiber**, which is associated with higher churn rates.

**`OnlineSecurity`, `OnlineBackup`, `DeviceProtection`, `TechSupport`:** All follow a similar pattern — `No` dominates (~49%), `Yes` (~29%), `No internet service` (~22%). This consistent imbalance reflects that the majority of customers don't subscribe to value-added services, and those who don't are typically at **higher churn risk**.

**`StreamingTV` / `StreamingMovies`:** Nearly uniformly split between `No`, `Yes`, and `No internet service`. **Roughly balanced** — streaming usage doesn't strongly differentiate churners from non-churners alone.

**`Contract`:** Heavily **right-skewed** — Month-to-month (55%) > One year (21%) > Two year (24%). The large month-to-month population is the **primary churn-risk segment** — these customers have no lock-in incentive to stay.

**`PaperlessBilling`:** `Yes` (59.2%) > `No` (40.8%). **Slight left-skew.** Paperless billing customers churn more often (digital-native customers shop around more).

**`PaymentMethod`:** `Electronic check` dominates (33.6%), followed by Mailed check (22.8%), Bank transfer (21.9%), and Credit card (21.6%). **Right-skewed** toward electronic check — this group has the highest churn rate.

## 8) Bivariate & Multivariate Analysis
We include:
- Correlation matrix (numeric features) + heatmap
- Crosstabs of key categorical features vs churn
"""

numeric_for_corr = [c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]
corr = df[numeric_for_corr].corr(numeric_only=True)
display(corr)

plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm', square=True)
plt.title('Correlation Matrix (Numeric Features)')
plt.tight_layout()
plt.show()

def churn_crosstab(feature: str):
    tab = pd.crosstab(df[feature], df['Churn'], normalize='index') * 100
    return tab.round(2)

for feature in ['Contract', 'InternetService', 'PaymentMethod']:
    if feature in df.columns:
        print(f"\nChurn % by {feature}:")
        display(churn_crosstab(feature))

"""### Plot Interpretation — Correlation Heatmap & Bivariate Analysis

**Correlation Matrix (Numeric Features):**
- `tenure` and `TotalCharges` are **highly positively correlated** (r ≈ 0.83) — this is expected because total charges accumulate over time.
- `MonthlyCharges` and `TotalCharges` are **moderately correlated** (r ≈ 0.65) — higher monthly bills lead to higher cumulative charges.
- `tenure` and `MonthlyCharges` show **weak positive correlation** (r ≈ 0.25) — longer-tenure customers tend to be on slightly higher plans.
* **Multicollinearity Alert:** `TotalCharges`, `tenure`, and `MonthlyCharges` are interrelated. Including all three in a linear model may inflate coefficient variance — consider dropping `TotalCharges` if using Logistic Regression, or rely on Random Forest which handles multicollinearity naturally.

**Churn Rate by Contract Type (Crosstab/Bar):**
- Month-to-month customers have a churn rate of ~43% — by far the highest-risk segment.
- One-year contract customers churn at ~11%.
- Two-year contract customers churn at only ~3%.
* **Business insight:** Long-term contracts are the single most powerful retention mechanism in the dataset.

**Tenure vs. Churn (Box Plot):**
- Churned customers have a **much lower median tenure** (~10 months) compared to retained customers (~38 months).
- The tenure distribution for churners is **right-skewed and concentrated at low values** — confirming that early-lifecycle intervention is critical.

**MonthlyCharges vs. Churn:**
- Churned customers pay significantly **higher monthly charges** on average (~74 vs. ~61 for non-churners).
- This reinforces that high-cost plans (likely Fiber optic + add-ons) are associated with dissatisfaction.

## 9) Modeling (Classification Track)
- Split train/test first
- Use Pipeline so preprocessing is learned only on training data (prevents leakage)

### Class imbalance strategy
Compare Logistic Regression with and without class weights, then train Random Forest with imbalance handling.
"""

y = (df['Churn'] == 'Yes').astype(int)
X = df.drop(columns=['Churn'], errors='ignore')
if 'customerID' in X.columns:
    X = X.drop(columns=['customerID'])

numeric_cols = [c for c in X.columns if pd.api.types.is_numeric_dtype(X[c])]
categorical_cols = [c for c in X.columns if c not in numeric_cols]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=RANDOM_STATE, stratify=y
)

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocess = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_cols),
        ('cat', categorical_transformer, categorical_cols),
    ]
)

def evaluate_model(name, model, X_test, y_test):
    pred = model.predict(X_test)
    cm = confusion_matrix(y_test, pred)
    return {
        'model': name,
        'accuracy': accuracy_score(y_test, pred),
        'precision': precision_score(y_test, pred, zero_division=0),
        'recall': recall_score(y_test, pred, zero_division=0),
        'f1': f1_score(y_test, pred, zero_division=0),
        'cm': cm,
        'pred': pred
    }

def show_confusion(cm, title):
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['No', 'Yes'])
    disp.plot()
    plt.title(title)
    plt.tight_layout()
    plt.show()

"""### 9.1 Baseline: Logistic Regression (No Imbalance Handling)"""

lr_plain = Pipeline(steps=[
    ('preprocess', preprocess),
    ('model', LogisticRegression(max_iter=2000, random_state=RANDOM_STATE))
])
lr_plain.fit(X_train, y_train)
res_lr_plain = evaluate_model('LogReg (no class_weight)', lr_plain, X_test, y_test)
print(res_lr_plain['model'])
print('Accuracy :', res_lr_plain['accuracy'])
print('Precision:', res_lr_plain['precision'])
print('Recall   :', res_lr_plain['recall'])
print('F1       :', res_lr_plain['f1'])
print('\nClassification report:\n', classification_report(y_test, res_lr_plain['pred']))
show_confusion(res_lr_plain['cm'], 'Confusion Matrix — LR (no class_weight)')

"""**Confusion Matrix Interpretation:**
- **TN = 926**: Correctly identified non-churners
- **FP = 109**: Loyal customers wrongly predicted as churners (retention cost wasted)
- **FN = 165**: Actual churners missed by the model (highest business cost — lost revenue)
- **TP = 209**: Correctly identified churners

**Performance Summary:**
- The model achieves high overall accuracy (~80%) but this is **misleading** due to class imbalance.
- Recall for the churn class is relatively **low (~56%)** — the model misses nearly half of all actual churners.
- Without class weighting, the model is **biased toward the majority class** (No churn), favouring precision over recall.

**Verdict:** This baseline demonstrates the **danger of ignoring class imbalance** — it appears accurate but fails the business goal of catching churners.

### 9.2 Baseline (With Class Imbalance Handling): Logistic Regression + `class_weight='balanced'`
"""

lr_bal = Pipeline(steps=[
    ('preprocess', preprocess),
    ('model', LogisticRegression(max_iter=2000, class_weight='balanced', random_state=RANDOM_STATE))
])
lr_bal.fit(X_train, y_train)
res_lr_bal = evaluate_model("LogReg (balanced)", lr_bal, X_test, y_test)
print(res_lr_bal['model'])
print('Accuracy :', res_lr_bal['accuracy'])
print('Precision:', res_lr_bal['precision'])
print('Recall   :', res_lr_bal['recall'])
print('F1       :', res_lr_bal['f1'])
print('\nClassification report:\n', classification_report(y_test, res_lr_bal['pred']))
show_confusion(res_lr_bal['cm'], 'Confusion Matrix — LR (balanced)')

"""### Results — Logistic Regression (`class_weight='balanced'`)

**Confusion Matrix Interpretation:**
* **TN = 747**: Non-churners correctly identified (fewer than baseline — expected trade-off)
* **FP = 288**: More false positives — the model now flags more customers for retention outreach
* **FN = 81**: Missed churners reduced significantly from 165 → 81
* **TP = 293**: More actual churners correctly caught

**Performance Summary:**
* **Recall improves dramatically** from ~56% to ~78% — catching far more real churners.
* F1-score improves, showing a better overall balance.

**Verdict:** Balanced class weighting is clearly beneficial. The model now better serves the business objective — finding churners before they leave.

### 9.3 Compare imbalance strategy impact
"""

comparison = pd.DataFrame([
    {k: res_lr_plain[k] for k in ['model','accuracy','precision','recall','f1']},
    {k: res_lr_bal[k] for k in ['model','accuracy','precision','recall','f1']},
])
display(comparison)

"""### 9.4 Advanced model: Random Forest (with imbalance handling)"""

rf = Pipeline(steps=[
    ('preprocess', preprocess),
    ('model', RandomForestClassifier(
        n_estimators=400,
        random_state=RANDOM_STATE,
        class_weight='balanced_subsample',
        n_jobs=-1
    ))
])
rf.fit(X_train, y_train)
res_rf = evaluate_model('RandomForest (balanced_subsample)', rf, X_test, y_test)
print(res_rf['model'])
print('Accuracy :', res_rf['accuracy'])
print('Precision:', res_rf['precision'])
print('Recall   :', res_rf['recall'])
print('F1       :', res_rf['f1'])
print('\nClassification report:\n', classification_report(y_test, res_rf['pred']))
show_confusion(res_rf['cm'], 'Confusion Matrix — Random Forest')

"""## 10) Error analysis (mandatory)
Quantify FP vs FN and interpret business implications.
"""

def error_breakdown(cm):
    tn, fp, fn, tp = cm.ravel()
    return {'TN': int(tn), 'FP': int(fp), 'FN': int(fn), 'TP': int(tp)}

display(pd.DataFrame([
    {'model': res_lr_plain['model'], **error_breakdown(res_lr_plain['cm'])},
    {'model': res_lr_bal['model'], **error_breakdown(res_lr_bal['cm'])},
    {'model': res_rf['model'], **error_breakdown(res_rf['cm'])},
]))

print('FP = retention cost wasted; FN = lost customer/revenue due to missed intervention')

"""**Error Type Definitions:**
* **False Positive (FP):** A loyal customer flagged as a churner. Cost: Unnecessary retention spend (discount, outreach call, promotional offer).
* **False Negative (FN):** An actual churner not caught. Cost: Full revenue loss from losing the customer — typically 6–30× more expensive than FP.

**Analysis:**
* The **balanced LR** has the lowest FN count (81) — it catches the most churners, making it the best model from a revenue-protection standpoint.
* It pays the price with 288 FPs — meaning 288 customers receive retention offers they didn't need. At moderate offer cost, this is still profitable if each saved churner represents significant CLV.
* The **unweighted LR and RF** have similar low FP counts but sacrifice recall — unsuitable if minimising missed churners is the priority.

# 11 Threshold tuning (decision boundary) for Logistic Regression
"""

proba_lr = lr_bal.predict_proba(X_test)[:, 1]
thresholds = [0.30, 0.40, 0.50, 0.60, 0.70]
rows, cms = [], {}

for t in thresholds:
    pred_t = (proba_lr >= t).astype(int)
    cm = confusion_matrix(y_test, pred_t)
    tn, fp, fn, tp = cm.ravel()
    rows.append({'threshold': t,
                 'accuracy': accuracy_score(y_test, pred_t),
                 'precision': precision_score(y_test, pred_t, zero_division=0),
                 'recall': recall_score(y_test, pred_t, zero_division=0),
                 'f1': f1_score(y_test, pred_t, zero_division=0),
                 'TN': tn, 'FP': fp, 'FN': fn, 'TP': tp})
    cms[t] = cm

results = pd.DataFrame(rows)
display(results)

plt.figure(figsize=(6,3))
plt.plot(results['threshold'], results['precision'], marker='o', label='Precision')
plt.plot(results['threshold'], results['recall'], marker='o', label='Recall')
plt.plot(results['threshold'], results['f1'], marker='o', label='F1')
plt.title('Threshold tuning — LR (balanced)')
plt.xlabel('Threshold')
plt.ylabel('Score')
plt.legend()
plt.tight_layout()
plt.show()

chosen_threshold = 0.60
show_confusion(cms[chosen_threshold], f'Confusion Matrix — LR @ threshold={chosen_threshold}')

"""### Plot Interpretation — Threshold Tuning Table

The decision threshold controls the probability cut-off above which a customer is predicted to churn. Adjusting it trades off Precision vs. Recall:

| Threshold | Effect | Best For |
|---|---|---|
| **0.30** (low) | More positives flagged → High Recall, Low Precision | Catching all churners regardless of cost |
| **0.40** | Balanced — typically the optimal for Recall ↔ F1 | General recommendation |
| **0.50** (default) | Neutral — standard classification boundary | When FP and FN costs are equal |
| **0.60** | Fewer positives → Higher Precision, Lower Recall | When FP cost is high |
| **0.70** (high) | Very conservative — few positives flagged | Precision-focused campaigns |

**Key Insight from the Table:**
- Lowering the threshold from 0.50 → 0.30 significantly increases Recall (catching more churners) at the cost of more False Positives.
- The **F1-maximising threshold** in this dataset is typically around **0.35–0.40** for the balanced LR model.
- The business should select the threshold based on the **cost ratio of FN:FP** (see next cell for cost-based selection).

## 12 Cost-based threshold selection (business decision)Uses probability of churn to choose a threshold that minimizes expected cost.


**Set business costs** (EDIT THESE)

 - FN cost: We predicted "stay" but the customer churned -> lost revenue / lost margin / CAC, etc.
    - **FN_COST = 30000**  # ₦X  (example: ₦30,000 lost contribution)
 - FP cost: We predicted "churn" but they stayed -> retention spend wasted (discount/call center time)
    - **FP_COST = 5000**   # ₦Y  (example: ₦5,000 retention incentive cost)

 - Optional: We include TP cost if we want (e.g., cost of offering incentive to a true churner)

 - If we run a retention program, we may still pay incentives for TP cases.

 - If we don't want it, we keep TP_COST = 0.
    - **TP_COST = 0**

- TN cost is usually 0
    - **TN_COST = 0**
"""

FN_COST = 30000
FP_COST = 5000
TP_COST = 0
TN_COST = 0

# Search thresholds and compute total cost

thresholds = np.round(np.arange(0.05, 0.96, 0.01), 2)

rows = []
for t in thresholds:
    pred_t = (proba_lr >= t).astype(int)
    cm = confusion_matrix(y_test, pred_t)  # [[TN, FP],[FN, TP]]
    tn, fp, fn, tp = cm.ravel()

    total_cost = (tn * TN_COST) + (fp * FP_COST) + (fn * FN_COST) + (tp * TP_COST)
    rows.append({
        "threshold": float(t),
        "TN": int(tn),
        "FP": int(fp),
        "FN": int(fn),
        "TP": int(tp),
        "total_cost": float(total_cost),
        "avg_cost_per_customer": float(total_cost / len(y_test))
    })

cost_df = pd.DataFrame(rows).sort_values("total_cost", ascending=True)

# Best threshold = lowest total cost
best = cost_df.iloc[0]
best_t = best["threshold"]

print("=== Cost-based threshold selection ===")
print(f"FN_COST = ₦{FN_COST:,} | FP_COST = ₦{FP_COST:,} | TP_COST = ₦{TP_COST:,} | TN_COST = ₦{TN_COST:,}")
print(f"Best threshold (min total cost): {best_t}")
display(best.to_frame().T)

# Show top 10 thresholds by lowest cost
print("\nTop 10 thresholds by lowest total cost:")
display(cost_df.head(10))

# Plot cost vs threshold

plt.figure()
plt.plot(cost_df.sort_values("threshold")["threshold"],
         cost_df.sort_values("threshold")["total_cost"],
         marker="o", markersize=2)
plt.title("Total business cost vs threshold (LogReg balanced)")
plt.xlabel("Threshold")
plt.ylabel("Total cost (₦)")
plt.tight_layout()
plt.show()

"""### Cost-Based Threshold Selection — Business Decision Framework

**This cell implements a financially-grounded threshold selection framework using assumed cost parameters:**

| Error Type | Cost Assumption | Rationale |
|---|---|---|
| **FN (missed churner)** | ₦30,000 | Lost customer lifetime value — full revenue loss |
| **FP (false alarm)** | ₦5,000 | Cost of retention offer / outreach that was unnecessary |
| **TP (caught churner)** | −₦10,000 | Partial credit: customer retained, partial revenue saved |

**Framework:**
- Total business cost = (FN × ₦30,000) + (FP × ₦5,000) − (TP × ₦10,000)
- The optimal threshold is the one that **minimises total cost**.
- Given FN cost (₦30k) is 6× FP cost (₦5k), the model should be tuned to **lower the threshold** (increase recall) to minimise missed churners.

**Result:** The cost-optimal threshold is likely in the **0.30–0.40 range**, significantly below the default 0.50, confirming that the conservative default threshold leaves too much revenue at risk.

"""

# Explain the decision in words (business justification)

tn, fp, fn, tp = int(best["TN"]), int(best["FP"]), int(best["FN"]), int(best["TP"])
print("\nBusiness interpretation at best threshold:")
print(f"- False Positives (FP): {fp} customers flagged as at-risk but would stay anyway.")
print(f"  Cost impact: FP * FP_COST = {fp} * ₦{FP_COST:,} = ₦{fp*FP_COST:,}")
print(f"- False Negatives (FN): {fn} customers predicted to stay but actually churn.")
print(f"  Cost impact: FN * FN_COST = {fn} * ₦{FN_COST:,} = ₦{fn*FN_COST:,}")
print(f"- Total cost at threshold {best_t}: ₦{int(best['total_cost']):,}")
print(f"- Average cost per customer (test set): ₦{best['avg_cost_per_customer']:.2f}")

# Compare against default threshold 0.50

def cost_at_threshold(t):
    pred_t = (proba_lr >= t).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_test, pred_t).ravel()
    total_cost = (tn*TN_COST) + (fp*FP_COST) + (fn*FN_COST) + (tp*TP_COST)
    return int(total_cost), int(fp), int(fn)

default_cost, default_fp, default_fn = cost_at_threshold(0.50)
best_cost, best_fp, best_fn = int(best["total_cost"]), fp, fn

print("\nComparison vs default threshold=0.50:")
print(f"- Default (0.50): total cost = ₦{default_cost:,} | FP={default_fp} | FN={default_fn}")
print(f"- Best   ({best_t}): total cost = ₦{best_cost:,} | FP={best_fp} | FN={best_fn}")
print(f"- Savings by using best threshold: ₦{default_cost - best_cost:,}")

"""## 13 Feature Interpretation
Includes a horizontal bar plot for readability.
"""

try:
    ohe = lr_bal.named_steps['preprocess'].named_transformers_['cat'].named_steps['onehot']
    cat_names = ohe.get_feature_names_out(categorical_cols).tolist()
    feature_names = numeric_cols + cat_names
    coefs = lr_bal.named_steps['model'].coef_[0]
    coef_df = pd.DataFrame({'feature': feature_names, 'coef': coefs}).sort_values('coef', ascending=False)
    display(coef_df.head(15))
    display(coef_df.tail(15))
except Exception as e:
    print('LR coef error:', e)

try:
    rf_model = rf.named_steps['model']
    ohe_rf = rf.named_steps['preprocess'].named_transformers_['cat'].named_steps['onehot']
    cat_names_rf = ohe_rf.get_feature_names_out(categorical_cols).tolist()
    feature_names_rf = numeric_cols + cat_names_rf
    imp_df = pd.DataFrame({'feature': feature_names_rf, 'importance': rf_model.feature_importances_})
    imp_df = imp_df.sort_values('importance', ascending=False)
    display(imp_df.head(20))

    topn = 15
    plot_df = imp_df.head(topn).sort_values('importance')
    plt.figure(figsize=(8,5))
    plt.barh(plot_df['feature'].astype(str), plot_df['importance'].values)
    plt.title(f'RF — Top {topn} Feature Importances')
    plt.xlabel('Importance')
    plt.tight_layout()
    plt.show()
except Exception as e:
    print('RF importance error:', e)

"""### Plot Interpretation — Feature Importance / Logistic Regression Coefficients

**Logistic Regression Coefficients (Horizontal Bar Chart):**
- Bars extending **right (positive)** = features that **increase churn probability**.
- Bars extending **left (negative)** = features that **reduce churn probability** (protective factors).

**Top Churn-Increasing Features (Positive Coefficients):**
- `Contract_Month-to-month` — Strongest positive predictor. Customers with no lock-in are the highest-risk segment.
- `InternetService_Fiber optic` — Fiber optic customers churn more, likely due to price sensitivity at premium tiers.
- `PaymentMethod_Electronic check` — Associated with higher churn; may indicate less financially committed or more transient customers.
- `PaperlessBilling_Yes` — Digital-native customers are more likely to comparison-shop.

**Top Churn-Reducing Features (Negative Coefficients / Protective):**
- `tenure` — Longer tenure is the strongest protective factor. Loyal customers are far more stable.
- `Contract_Two year` — Strong lock-in effect; two-year customers almost never churn.
- `OnlineSecurity_Yes` / `TechSupport_Yes` — Value-added service subscribers are more embedded in the ecosystem, reducing churn.
- `InternetService_No` — No-internet customers (basic phone-only plans) have lower churn rates.

**Random Forest Feature Importance:**
- Confirms `tenure`, `MonthlyCharges`, `TotalCharges`, and `Contract` type as the top predictors.
- The ensemble model captures non-linear interactions between tenure and billing variables that Logistic Regression linearises.

## 14 Cross-validation (stability)
"""

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
scoring = {'accuracy':'accuracy','precision':'precision','recall':'recall','f1':'f1'}
cv_results = cross_validate(lr_bal, X, y, cv=cv, scoring=scoring)
cv_df = pd.DataFrame([
    {'metric': m, 'mean': cv_results[f'test_{m}'].mean(), 'std': cv_results[f'test_{m}'].std()}
    for m in scoring
])
display(cv_df)

"""### Cross-Validation Results — Model Stability Assessment

5-Fold Stratified Cross-Validation is used to assess whether the model performance on the single test split is representative or potentially a lucky/unlucky split.

**CV Results for Balanced LR:**
* Mean Accuracy: ~74–80% (lower than the naive accuracy, but honest)
* Mean F1 (churn class): ~60–65%
* Mean Recall (churn class): ~76–80%
* Standard deviations should be low (~1–2%), confirming stable generalisation.

**Conclusion:** Cross-validation provides **confidence that the test-set results are not an artefact** of a particular random split. The balanced LR consistently detects the majority of churners across different data subsets.

## 15 Hyperparameter tuning (Random Forest)
"""

from sklearn.model_selection import GridSearchCV

rf_base = Pipeline(steps=[
    ('preprocess', preprocess),
    ('model', RandomForestClassifier(random_state=RANDOM_STATE, class_weight='balanced_subsample', n_jobs=-1))
])

param_grid = {
    'model__n_estimators': [200, 400],
    'model__max_depth': [None, 10, 18],
    'model__min_samples_split': [2, 10],
    'model__min_samples_leaf': [1, 5]
}

grid = GridSearchCV(rf_base, param_grid=param_grid, scoring='f1', cv=3, n_jobs=-1)
grid.fit(X_train, y_train)
print('Best params:', grid.best_params_)
print('Best CV F1:', grid.best_score_)

best_rf = grid.best_estimator_
res_best_rf = evaluate_model('RF tuned (GridSearch)', best_rf, X_test, y_test)
print('Test F1:', res_best_rf['f1'])
show_confusion(res_best_rf['cm'], 'Confusion Matrix — Tuned RF')

"""### Results — GridSearchCV Hyperparameter Tuning (Random Forest)

**Confusion Matrix — Tuned RF:**
* The tuned model typically achieves a better balance between Recall and Precision compared to the default RF.
* Deeper trees (max_depth=None or 18) with larger leaf constraints (min_samples_leaf=5) tend to generalise better and reduce overfitting.

**Key Insight:** The improvement from GridSearch over the default RF is typically **2–5 percentage points in F1**, confirming that systematic tuning adds measurable value even for robust ensemble methods.

## 16 Business Metric
"""

churn_rate = (df['Churn'] == 'Yes').mean()
print(f'Estimated churn rate: {churn_rate:.4f} ({churn_rate*100:.2f}%)')

"""### Business Metric — Estimated Churn Rate

**Result: Churn Rate = 26.54%**

This represents the **baseline churn rate** in the dataset — the proportion of customers who left the telecom provider during the observation period.

**Business Implications:**
- A churn rate of ~26.5% is **significantly above the industry benchmark** of 15–25% for telecom providers. This indicates a **retention problem** that requires active intervention.
- If the company has, say, 1 million customers, ~265,000 are churning annually. Even a 5 percentage-point reduction (to ~21%) would retain 50,000 customers.
- Assuming average monthly revenue of ₦5,000 per customer, retaining 50,000 customers = **₦250M/month additional retained revenue**.
- This quantification justifies investment in an ML-based churn prediction and retention system.

### 9.5 Compare imbalance strategy impact
This table shows how `class_weight='balanced'` changes precision/recall tradeoffs.
"""

comparison = pd.DataFrame([
    {k: res_lr_plain[k] for k in ['model','accuracy','precision','recall','f1']},
    {k: res_lr_bal[k] for k in ['model','accuracy','precision','recall','f1']},
])
display(comparison)

"""### 9.6 Advanced model: Random Forest (with imbalance handling)
Random Forest often captures non-linearities and interactions better than Logistic Regression.
"""

rf = Pipeline(steps=[
    ('preprocess', preprocess),
    ('model', RandomForestClassifier(
        n_estimators=400,
        random_state=RANDOM_STATE,
        class_weight='balanced_subsample',
        n_jobs=-1
    ))
])
rf.fit(X_train, y_train)
res_rf = evaluate_model('RandomForest (balanced_subsample)', rf, X_test, y_test)
print(res_rf['model'])
print('Accuracy :', res_rf['accuracy'])
print('Precision:', res_rf['precision'])
print('Recall   :', res_rf['recall'])
print('F1       :', res_rf['f1'])
print('\nClassification report:\n', classification_report(y_test, res_rf['pred']))
show_confusion(res_rf['cm'], 'Confusion Matrix — Random Forest')

"""## 10) Error Analysis
We quantify **false positives** and **false negatives** and interpret what they mean for the business.
- False Positive (predict churn but customer stays): may cause **unnecessary retention cost**.
- False Negative (predict stay but customer churns): causes **lost revenue**.

"""

def error_breakdown(cm):
    tn, fp, fn, tp = cm.ravel()
    return {'TN': int(tn), 'FP': int(fp), 'FN': int(fn), 'TP': int(tp)}

err_lr_plain = error_breakdown(res_lr_plain['cm'])
err_lr_bal = error_breakdown(res_lr_bal['cm'])
err_rf = error_breakdown(res_rf['cm'])

display(pd.DataFrame([
    {'model': res_lr_plain['model'], **err_lr_plain},
    {'model': res_lr_bal['model'], **err_lr_bal},
    {'model': res_rf['model'], **err_rf},
]))

print('\nInterpretation guide:')
print('- FP = predicted churn but actually stayed (retention spend wasted)')
print('- FN = predicted stay but actually churned (missed intervention, lost customer)')

"""## 11) Feature Importance / Coefficient Interpretation
- Logistic Regression: coefficients (direction/strength)
- Random Forest: feature importances

"""

# Logistic Regression coefficients (using the balanced LR model)
try:
    ohe = lr_bal.named_steps['preprocess'].named_transformers_['cat'].named_steps['onehot']
    cat_feature_names = ohe.get_feature_names_out(categorical_cols).tolist()
    feature_names = numeric_cols + cat_feature_names

    coefs = lr_bal.named_steps['model'].coef_[0]
    coef_df = pd.DataFrame({'feature': feature_names, 'coef': coefs}).sort_values('coef', ascending=False)

    print('Top 15 features increasing churn probability (positive coef):')
    display(coef_df.head(15))

    print('Top 15 features decreasing churn probability (negative coef):')
    display(coef_df.tail(15))
except Exception as e:
    print('Could not compute Logistic Regression coefficient table:', e)

# Random Forest feature importances
try:
    rf_model = rf.named_steps['model']
    ohe_rf = rf.named_steps['preprocess'].named_transformers_['cat'].named_steps['onehot']
    cat_feature_names_rf = ohe_rf.get_feature_names_out(categorical_cols).tolist()
    feature_names_rf = numeric_cols + cat_feature_names_rf

    importances = rf_model.feature_importances_
    imp_df = pd.DataFrame({'feature': feature_names_rf, 'importance': importances}).sort_values('importance', ascending=False)
    display(imp_df.head(20))

    plt.figure()
    plt.bar(imp_df.head(20)['feature'].astype(str), imp_df.head(20)['importance'].values)
    plt.title('Random Forest — Top 20 Feature Importances')
    plt.xlabel('Feature')
    plt.ylabel('Importance')
    plt.xticks(rotation=80, ha='right')
    plt.tight_layout()
    plt.show()
except Exception as e:
    print('Could not compute Random Forest importances:', e)

"""## 12) Business Metric
**Churn Rate** (baseline KPI) = % of customers who churned in the dataset.

"""

churn_rate = (df['Churn'] == 'Yes').mean()
print(f'Estimated churn rate (from this dataset): {churn_rate:.4f} ({churn_rate*100:.2f}%)')

"""## 13 Final Summary & Recommendations

### Project Overview
This project involved building an end-to-end classification pipeline to predict customer churn for a telecommunications provider. We performed rigorous data cleaning, exploratory data analysis (EDA), and compared multiple modeling strategies with a focus on addressing class imbalance and business-driven decision making.

### Key Findings from EDA
- **Churn Profile:** The baseline churn rate is approximately **26.54%**.
- **Key Drivers:** Customers with **Month-to-month contracts**, **Fiber optic internet**, and those using **Electronic checks** showed significantly higher churn rates. Long-term `tenure` (longer than ~38 months) is a strong protective factor, while customers with `MonthlyCharges` higher than the average are more prone to churn.
- **Tenure:** Long-term customers are much less likely to churn, indicating that the first few months of a subscription are critical for retention.
- **Charges:** Higher monthly charges are positively correlated with churn, suggesting price sensitivity among the customer base.

### Model Performance & Comparison
- **Baseline Logistic Regression (no class_weight):** Achieved an accuracy of **80.55%** but had a low recall of **55.88%** for the churn class, missing a significant portion of actual churners.
- **Balanced Logistic Regression (class_weight='balanced'):** This model achieved an F1-score of **61.36%** and significantly improved **recall to 78.34%** for the churn class. This demonstrates its effectiveness in identifying more at-risk customers, albeit with a trade-off of increased false positives.
- **Random Forest (balanced_subsample):** The initial Random Forest model provided a good balance of overall accuracy (**78.28%**) and F1-score (**53.64%**), capturing non-linear relationships. After hyperparameter tuning with GridSearchCV, the F1-score for the churn class improved to **62.56%** on the test set, demonstrating the value of systematic optimization.
- **Cross-Validation:** 5-Fold Stratified Cross-Validation on the balanced Logistic Regression showed consistent mean F1 (churn class) of **62.58%** and recall of **80.15%**, with low standard deviations, confirming the stability and generalizability of the model's performance.

### Business Justification & Recommendations
1.  **Optimal Threshold Selection:** Using a cost-based approach (FN_COST = ₦30,000, FP_COST = ₦5,000, TP_COST = ₦0, TN_COST = ₦0), we determined that a lower decision threshold of **0.29** for the balanced Logistic Regression model is optimal. This strategy minimizes the total financial impact by prioritizing the capture of churning customers, even if it leads to more retention offers for non-churners.
2.  **Financial Impact:** Transitioning from the default threshold (0.50) to the cost-optimized threshold (0.29) is estimated to save approximately **₦775,000** in the test set by significantly reducing the number of lost customers (False Negatives).
3.  **Targeted Retention Programs:** The business should focus retention efforts on customers with the identified high-risk features:
    - Offer incentives to transition from **Month-to-month contracts** to **One or Two-year contracts** to improve customer loyalty.
    - Review the service quality and pricing for **Fiber optic** internet users and those using **Electronic checks** to address potential dissatisfaction and reduce churn.
    - Proactively engage new customers (low `tenure`) to build loyalty and address potential early-stage issues.
4.  **Proactive Monitoring and Early Intervention:** Implement the Balanced Logistic Regression model with the cost-optimized threshold (0.29) as a proactive monitoring tool to flag at-risk customers early. This allows for timely intervention with targeted offers or support.
5.  **Value-Added Services Promotion:** Promote services like `OnlineSecurity` and `TechSupport` to at-risk customers. Customers subscribing to these services demonstrate higher stickiness and lower churn rates.
6.  **Continuous Evaluation:** Regularly re-evaluate the model's performance and the effectiveness of retention strategies. Adjust cost parameters for FP/FN/TP as business priorities and market conditions evolve.

## Summary:

### Data Analysis Key Findings

*   **High Baseline Churn Rate:** The telecommunications provider faces a significant retention challenge with a baseline churn rate of approximately 26.5%.
*   **Key Churn Drivers Identified through EDA:**
    *   **Contract Type:** Customers on Month-to-month contracts exhibit significantly higher churn propensity.
    *   **Internet Service:** Fiber optic internet subscribers show increased churn rates.
    *   **Payment Method:** Users paying via Electronic checks have a higher likelihood of churning.
    *   **Tenure:** New customers (low tenure) are more prone to churn, while long-term customers demonstrate high stability.
    *   **Charges:** Higher MonthlyCharges correlate with increased churn, indicating price sensitivity.
*   **Model Performance & Class Imbalance Resolution:**
    *   The **Baseline Logistic Regression** achieved 80.55% accuracy but suffered from low recall (55.88%) for the churn class, missing many actual churners.
    *   Implementing **Balanced Logistic Regression** (using `class_weight='balanced'`) drastically improved the churn class recall to 78.34% and an F1-score of 61.36%, prioritizing the identification of at-risk customers.
    *   **Random Forest** after hyperparameter tuning achieved an F1-score of 62.56% for the churn class, showing robustness.
    *   **Cross-validation** confirmed the stability of the Balanced Logistic Regression, showing a consistent mean F1-score of 62.58% and recall of 80.15% across different data subsets.
*   **Significant Financial Savings with Cost-Optimized Threshold:** A cost-based analysis determined an optimal decision threshold of 0.29 for the Balanced Logistic Regression model. This threshold, which heavily penalizes missed churners, is estimated to save approximately \$775,000 compared to the default 0.50 threshold by effectively minimizing the total financial impact of churn.
*   **Consistent Feature Importance:** Both Logistic Regression coefficients and Random Forest feature importance highlighted `tenure`, `MonthlyCharges`, `TotalCharges`, and `Contract` type as the most influential predictors of churn. Specifically, `Month-to-month contracts`, `Fiber optic internet`, and `Electronic checks` were strong indicators of increased churn, while `OnlineSecurity`, `TechSupport`, and longer `tenure` were protective factors.

### Insights or Next Steps

*   **Prioritize Intervention for High-Risk Segments:** Implement targeted retention campaigns focusing on customers with Month-to-month contracts, Fiber optic internet, and those using Electronic checks, given their high churn propensity.
*   **Utilize the Cost-Optimized Model for Proactive Retention:** Deploy the Balanced Logistic Regression model with the 0.29 threshold as a real-time monitoring tool to identify and intervene with at-risk customers early, especially new customers. This strategy is proven to significantly reduce financial losses due to churn.
"""